version: '3.8'

services:
  # Исходная БД (имитация текущей системы с UUID v4)
  source_db:
    image: postgres:15
    container_name: source_postgres
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Целевая БД (оптимизированная база с Integer/BigInt)
  target_db:
    image: postgres:15
    container_name: target_postgres
    environment:
      POSTGRES_DB: target_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"